import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Geist, Source_Serif_4, JetBrains_Mono } from "next/font/google"
import { cn } from "@ph/ui"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

const geist = Geist({ subsets: ['cyrillic', 'latin', 'latin-ext'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], variable: '--font-geist' });

const sourceSerif4 = Source_Serif_4({ subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'vietnamese'], weight: ['200', '300', '400', '500', '600', '700', '800', '900'], variable: '--font-source-serif-4' });

const jetBrainsMono = JetBrains_Mono({ subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'vietnamese'], weight: ['100', '200', '300', '400', '500', '600', '700', '800'], variable: '--font-jetbrains-mono' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("antialiased", geist.variable, sourceSerif4.variable, jetBrainsMono.variable)}>
      <body className="">
        {children}
      </body>
    </html>
  );
}
